# Generated by Django 5.0.6 on 2024-06-13 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tienda", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoriaproducto",
            old_name="nombre_categoria",
            new_name="nombre",
        ),
        migrations.RenameField(
            model_name="producto",
            old_name="categoria_producto",
            new_name="categoria",
        ),
        migrations.RenameField(
            model_name="producto",
            old_name="descripcion_producto",
            new_name="descripcion",
        ),
        migrations.RenameField(
            model_name="producto",
            old_name="disponibilidad_producto",
            new_name="disponibilidad",
        ),
        migrations.RenameField(
            model_name="producto",
            old_name="imagen_producto",
            new_name="imagen",
        ),
        migrations.RenameField(
            model_name="producto",
            old_name="nombre_producto",
            new_name="nombre",
        ),
        migrations.RenameField(
            model_name="producto",
            old_name="precio_producto",
            new_name="precio",
        ),
    ]
