# Generated by Django 5.0.6 on 2024-06-18 03:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0002_rename_pedido_id_lineapedido_pedido_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lineapedido",
            options={
                "ordering": ["id"],
                "verbose_name": "Lineapedido",
                "verbose_name_plural": "Linea Pedidos",
            },
        ),
        migrations.AlterModelTable(
            name="lineapedido",
            table="Lineapedidos",
        ),
    ]
