# Generated by Django 5.0.6 on 2024-06-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="contenido",
            field=models.TextField(),
        ),
    ]
